# ==============================================================================
# NOTE: LEVEL 3 METRIC CALCULATION SCRIPT
# This script calculates pooled C-indices from out-of-fold prediction logs
# generated by code/06_run_nested_cv.R. Patient-level prediction logs are not
# redistributed in the public release per privacy policy; published summary
# metrics are distributed in results/nested_cv_285_fold_metrics.csv.
# ==============================================================================
library(data.table)
library(survival)

oof <- fread("nested_cv_285_patient_oof_predictions.csv")

cat("=== POOLED COHORT C-INDEX PER REPEAT (N = 285) ===\n")
models <- c("lasso", "enet", "xgb", "rf")
model_names <- c("LASSO-Cox", "ElasticNet", "XGBoost-AFT", "RandomSurvivalForest")

for (m_idx in seq_along(models)) {
  m <- models[m_idx]
  m_name <- model_names[m_idx]
  col_risk <- paste0("risk_", m)
  
  rep_c <- numeric(5)
  for (r in 1:5) {
    sub <- oof[repeat_id == r]
    surv_obj <- Surv(sub$os_time_days, sub$os_event)
    rep_c[r] <- as.numeric(concordance(surv_obj ~ I(-sub[[col_risk]]))$concordance)
  }
  cat(sprintf("%-22s | Rep 1: %.4f | Rep 2: %.4f | Rep 3: %.4f | Rep 4: %.4f | Rep 5: %.4f | Pooled Mean: %.4f (SD: %.4f)\n",
              m_name, rep_c[1], rep_c[2], rep_c[3], rep_c[4], rep_c[5], mean(rep_c), sd(rep_c)))
}
